name: sync

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 */8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-aliyun:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        . /etc/os-release
        #echo "deb https://download.opensuse.org/repositories/home:/kubeinit/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/home-kubeinit.list
        #curl -L https://download.opensuse.org/repositories/home:/kubeinit/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
        curl -O https://download.opensuse.org/repositories/home:/kubeinit/xUbuntu_20.04/amd64/skopeo_1.10.0-1_amd64.deb
        sudo apt-get update
        #sudo apt-get -y upgrade
        #sudo apt-get -y install skopeo
        dpkg -i skopeo_1.10.0-1_amd64.deb
        skopeo --version
    - name: generate_sync_yaml
      timeout-minutes: 30
      run: |
        python generate_sync_yaml.py
    
    - name: sync image
      env:
        HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
        HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
      run: |
        bash sync.sh
